#!/bin/sh
. "$(dirname "$0")/_/husky.sh"


echo '👷👷👷🛠 Styling, testing and building your project before committing 🛠👷👷👷'

npm run check-types || (
    echo '🤡😂❌🤡 Failed Type Check 🤡😂❌🤡
            Are you seriously trying to write that? Make the changes required above'
    false;
)

npm run check-format || 
(
    echo '🤢🤮🤢🤮 Your styling looks disgusting 🤢🤮🤢🤮
            Prettier Check Failed. Run npm run format, add changes and try to commit again.'
    false;
)

npm run check-lint || 
(
    echo '😤🏀👋😤 Take out that part! 😤🏀👋😤
            ESlint Check Failed. Make the required changes listed above, add changes and try to commit again.'
    false;
)

echo '🤔🤔🤔🤔... Allright... Code looks good to me... Trying to build now 🤔🤔🤔🤔'

npm run build || (
    echo '❌👷🔨❌ Your build failed ❌👷🔨❌
            Next build failed: View the errors above to see why' 
    false;
)

echo '✅✅✅✅ You win this time... I am commiting this now. ✅✅✅✅'


